# Generated by Django 6.0.5 on 2026-05-25 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone_offset',
            field=models.IntegerField(default=3, help_text="Hours offset from UTC. Used to localize 'hour of day' stats.", validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(14)]),
        ),
    ]
